#!/bin/sh

die() {
  local pattern="$1"
  shift
  printf "$pattern" "$@"
  exit 64
}

[ $# -eq 1 ] || die '%s: <env>\n' $0

env=$(readlink -f $1)

. $env

[ -n "$host" ] || die 'no host in %s\n' $env
[ -n "$roles" ] || die 'no roles in %s\n' $env

user=${user:-root}
repo=$(basename $(dirname $(readlink -f $0)))
run=run.sh
dest=/tmp/$repo

mkrun() {
  local exported rolescripts

  exported=$(grep '^_' < $env | sed 's/^/export /')
  for role in $roles; do
    rolescripts="${rolescripts}
${dest}/roles/${role}.sh"
  done

  cat <<EOF > $run
#!/bin/sh

set -e

PATH=$dest/bin:"\$PATH"

$exported
$rolescripts
EOF
chmod 700 $run
}

mkrun

(
  cd ..
  tar cpf - $repo | ssh $user@$host "tar xpf - -C $(dirname $dest)"
)

ssh $user@$host $dest/$run

rm $run
