#!/bin/sh

self=$0
env=
debug=
user=${user:-root}
repo=$(basename $(dirname $(readlink -f $self)))
run=run.sh
dest=/tmp/$repo

die() {
  printf "$@" >&2
  exit 64
}

parse() {
  [ $# -eq 1 -o $# -eq 2 ] || die '%s: <env> [--debug]\n' $self

  env=$(readlink -f $1)
  . $env

  [ -n "$host" ] || die 'no host in %s\n' $env
  [ -n "$roles" ] || die 'no roles in %s\n' $env

  [ $# -ne 2 -o "$2" != '--debug' ] || debug='set -x'
}

remote() {
  [ $host != localhost ]
}

mkrun() {
  cat <<EOF > $run
#!/bin/sh
$debug
$(sed '/^_/!d; s/^/export /' $env)
EOF

  cat bin/*.sh roles/*.sh handlers/*.sh >> $run

  printf '%s_role || exit 1\n' $roles >> $run
  chmod 700 $run
}

sync() {
  remote || return 0
  (
    cd ..
    tar cpf - $repo/$run $repo/templates \
      | ssh $user@$host "tar xpf - -C $(dirname $dest)"
  )
}

execrun() {
  if remote; then
    ssh $user@$host $dest/$run
  else
    ./$run
  fi
}

parse "$@" && mkrun && sync && execrun
rm -f $run
